### ISSUE TITLE
Problem when logout and instant login again

### ISSUE THREAD

**Issue by besteFinanzen** [fa-fifi/keycloak_wrapper#33]
Hi everyone,

I have the issue that when I log the user out and the user just logs back in after the logout ist done. I get this error printed:
`oneway function results for code 9 on binder at 0x7ae329fd3570 will be dropped but finished with status UNKNOWN_TRANSACTION`
And the same thing eleven times more. 

But I don't get any error in flutter itself, which I would be able to catch.
Did anyone of you also experience this issue?

**Comment by fa-fifi** [comment]
Is this happens during debugging on emulator?

**Comment by besteFinanzen** [comment]
Yeah, is this a known issue?

**Comment by fa-fifi** [comment]
It might be caused by cache issue. Try delete the app and reinstall the app again.

**Comment by fa-fifi** [comment]
@besteFinanzen is it resolved?

**Comment by besteFinanzen** [comment]
Sorry for late reply.
Yeah there seemed to be an issue with some things in cache. I experienced the problems multiple times but I think it has to do with the hot reload function of flutter. But if you just hot restart everything works fine.

Thanks for quick help @fa-fifi and nice package by the way, really helpfull and easy to integrate.

**Comment by yourior** [comment]
i got this problem again, it manage to create the new token, but on my api it return not authorized, but the problem doesnt show when i close and reopens the app , might be nice to have a debug log, to see the stream / auth process
