### ISSUE TITLE
Provide a way to reset the wrapper

### ISSUE THREAD

**Issue by lyio** [fa-fifi/keycloak_wrapper#42]
The authentication data stored in secure storage is automatically synced by iOS into iCloud and is restored on new installs.
So once authenticated there seems to be now way to actually get rid of the authentication again.

Could we provide a way to log users out locally, without needing to end the session server side? So that I can clear out stale authentication data for new installs?

**Comment by fa-fifi** [comment]
Okay, CMIIW.

Let's say there is a user that has an iPhone and an iPad, and both of his devices use the same Apple ID. If he login into your app using his iPhone, a session will be registered on the server side. If he installs your app on his iPad, he is automatically logged in since his authentication data is synced across all his Apple devices.

So now, you don't want that to happen. You want your user to login again when they install your app on another device, right?

**Comment by lyio** [comment]
Well, I haven't considered that case, but yes, kind of. As a user I would find that weird. 

My biggest problem with the current behavior is that I cannot clear the authentication data for testing/qa purposes even when reinstalling the App.

My App has kind of a two-stop login process where users first connect to a tenant specific backend system and then login to the respective keycloak instance. So with iOS restoring the login data, the App thinks it is already authenticated after the first step because iOS restores everything `keycloak_wrapper` stored in secure storage. But the Keycloak token does not necessarily work now anymore.

Does that make sense?

**Comment by fa-fifi** [comment]
Secure storage should be cleared after the user logs out from the previous session. Do you want to terminate the session when the user has logged in and delete the app so that when they reinstall the app on the same device, they will not be automatically logged in?

**Comment by lyio** [comment]
Yes, exactly. But since I don't think there is a callback to the App when it is uninstalled I would simply keep track of whether this is a fresh install and clear out any authentication data. I would really appreciate if `keycloak_wrapper` provided a way to do that, so I don't have to mess with the internals here.

**Comment by fa-fifi** [comment]
Alright, understood. Give me a few days and I'll get it done.
