### ISSUE TITLE
How to remove the offline_access scope

### ISSUE THREAD

**Issue by ahmadjie** [fa-fifi/keycloak_wrapper#47]
I am try using the Keycloak wrapper package in my Flutter project, and I need to modify the scopes being sent. Specifically, I would like to remove the offline_access scope. Could you please advise on how I can remove the offline_access scope

Thank you

**Comment by fa-fifi** [comment]
Sorry for the late reply.

May I know the reason why would you want to remove it?

**Comment by ahmadjie** [comment]
I want to remove "offline_access" because our backend specifically requires a type **refresh** for re-authentication.

**Comment by fa-fifi** [comment]
@ahmadjie
I've update the package to exclude "offline_access" from the default scope value. You can use the latest version v1.4.3.
