### ISSUE TITLE
On keycloak redirect back after succes login app crashes

### ISSUE THREAD

**Issue by jaderdev** [fa-fifi/keycloak_wrapper#48]
![Captura de Tela 2024-10-24 às 03 56 59](https://github.com/user-attachments/assets/f413b177-bd00-49ec-9cdb-53ac96efe58a)

My keycloak

![Captura de Tela 2024-10-24 às 03 57 30](https://github.com/user-attachments/assets/c0fc5049-49da-4e88-a00e-250bf0807b7a)
 
The error I get after a successful login!

![Captura de Tela 2024-10-24 às 03 58 27](https://github.com/user-attachments/assets/ce55a142-1875-4e51-a5f1-384d3b2c1071)

My build gradle

Im using the example aplication and my keycloak its working well! But when it redirects to the app i receive this error!

Could you help me?

![Captura de Tela 2024-10-24 às 03 59 47](https://github.com/user-attachments/assets/467543b3-1831-464a-bafe-59f7073d3ae4)

My config

**Comment by fa-fifi** [comment]
Hi, there.

I'm just saying that I'm quite busy this week. So, I'll look at this issue again later. Maybe tomorrow or the day after. I'm so sorry for the inconvenience. But in case you have resolved the issue, maybe you can share your findings here.

My only suggestion for now is maybe you can downgrade the package version to see whether the problem only occurs for the latest version or not. Hope that helps.

**Comment by jaderdev** [comment]
OK man, I still not solved the problem! But ill try downgrade and try again, thanks!

**Comment by jaderdev** [comment]
Man, one more question. Did you had success redirecting from keycloak right to the app?

**Comment by fa-fifi** [comment]
Yup, most of the time and my company also using this package in production.

I afraid this issue might only happens on the latest version due to dependecies update. However, please read through the documentation thoroughly so you won't miss any important details.

**Comment by jaderdev** [comment]
Which is the version you are using in your Company? Do you know the keycloak version? The problem im having is inside android where the keycloak redirect uses http not https and Android guess its insecure!

**Comment by fa-fifi** [comment]
If you are using http, you have to allow insecure http connection on your android app. Have you checked out this [guide](https://docs.flutter.dev/release/breaking-changes/androidx-migration)?

**Comment by jaderdev** [comment]
The question is that Im not running http, im running https but it is changing to http!

**Comment by fa-fifi** [comment]
Mmm... I've tried using the example app and it is working fine logging to my keycloak server.

I don't think your issue is a configuration issue, but maybe your keycloak server is behind a firewall that your emulator can't reach. Or you have to double check your input value or something. I'm also not sure, but the last thing I can do to help you is thru a video call.

**Comment by jaderdev** [comment]
Man, you're a great guy! Thanks for be so willing to help. Maybe we can make a video call and solve this. How is your schedule?

**Comment by fa-fifi** [comment]
Add me on Linkedin and we'll discuss there.

**Comment by ecolque** [comment]
I have same problem, on keycloakc redirect back after success login app not receive the code.
i review my keycloack credential it is ok.
<img width="424" alt="Screenshot 2024-11-06 at 14 13 10" src="https://github.com/user-attachments/assets/d5e7e752-43ce-48fb-8755-282687dcf63d">
click in the first icon the message: login failed 

![Screenshot_2024-11-06-14-10-37-731-edit_com android chrome](https://github.com/user-attachments/assets/c49f3e4d-97a4-45ec-bd80-4973dfc4314b)
click in the second icon the message: No stored state - unable to handle response

**Comment by fa-fifi** [comment]
@ecolque
Remove `android:taskAffinity=""` from your AndroidManifest.xml file.
