### ISSUE TITLE
Can't push branch.

### ISSUE THREAD

**Issue by vcherneny** [fa-fifi/keycloak_wrapper#53]
Hello @fa-fifi, i would like to create PR with small enhancement. I'm getting error when pushing new branch.

Can you please allow me to contribute? Thanks!

**Comment by vcherneny** [comment]
```
ERROR: Permission to fa-fifi/keycloak_wrapper.git denied to vcherneny.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by fa-fifi** [comment]
You have to fork the repo first in order to contribute.

**Comment by vcherneny** [comment]
Thanks @fa-fifi :) Closing the issue.
