### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by fa-fifi** [fa-fifi/keycloak_wrapper#9]
Create unit tests for every authentication methods inside the KeycloakWrapper class.

**Comment by DeleMike** [comment]
Hey @fa-fifi, this issue looks interesting to me.
I would like to learn more about testing. Can you help clarify what are the aim and objectives here?

Ty!

**Comment by fa-fifi** [comment]
Cool @DeleMike 👍
I am quite busy lately, so I really hoping someone could help me with this. The aim for the tests is only to verify the pull request made by collaborators, so they won't break any business logic. If possible, make sure to cover every available public methods. Take your time to study and create the tests. Thank you in advance. 🙂

**Comment by DeleMike** [comment]
Thanks for the explanation @fa-fifi,

I need extra clarification though:
- > The aim for the tests is only to verify the pull request made by collaborators, so they won't break any business logic. 

What do you mean by this? do you mean that when someone makes a PR we should validate it. How do you propose this should be done? What I know is we can encourage contributors to write a test case for every public API they introduce.

Could you help clarify this?

And yes, I will study the codebase and introduce test cases as fit. 

Thanks.
